import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import React from "react";
import {Navbar} from "@/components/Navbar";
import {ConfigAxios} from "@/components/ConfigAxios";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full bg-white" lang="en">
    <StoreProvider>
      <ConfigAxios>
      <body className="h-full">
        <Navbar/>
        {children}
      </body>
      </ConfigAxios>
    </StoreProvider>
    </html>
  );
}
