version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

  nextjs:
    build: ../frontend
    container_name: nextjs-app
    ports:
      - '3000:3000'
    volumes:
      - ../frontend:/app
      - /app/node_modules